[project]
site_name = "readme-assert"
site_url = "https://laat.github.io/readme-assert/"
repo_url = "https://github.com/laat/readme-assert"
repo_name = "laat/readme-assert"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.toc]
permalink = true
